// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modification_commentaire_et_repport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modification_commentaire_et_repport));
        
        string IMigrationMetadata.Id
        {
            get { return "201812072249403_Modification_commentaire_et_repport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
