// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajout_des_tables_medicalPath_et_chats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajout_des_tables_medicalPath_et_chats));
        
        string IMigrationMetadata.Id
        {
            get { return "201811082002006_Ajout_des_tables_medicalPath_et_chats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
