// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modif_medicalpath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modif_medicalpath));
        
        string IMigrationMetadata.Id
        {
            get { return "201812141823213_Modif_medicalpath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
